name: Lint & Test

on:
  workflow_dispatch: # allows manual trigger
  push: # only triggers on push events from non-stable branches
    branches-ignore:
      - main
      - beta
      - alpha
  pull_request:
    branches:
      - main # only works on PRs with base_ref=main and follows limits below

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Run linters
        run: pnpm lint

  test:
    needs: lint
    uses: ./.github/workflows/test.yml
    with:
      node_version: ${{ matrix.node }}
      run_integration_tests: true
      run_unit_tests: true
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
          - 23