name: Publish

on: 
  push: 
    branches:
      - main
      - beta
      - alpha

jobs:
  test: 
    name: 'Node.js v${{ matrix.node }}'
    uses: ./.github/workflows/test.yml
    with:
      node_version: ${{ matrix.node }}
      run_integration_tests: true
      run_unit_tests: true
      run_e2e_tests: true
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
          - 23

  release:
    name: Release
    needs: test
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build --if-present
      - run: npx release-it --ci --dry-run

  prerelease:
    needs: test
    name: PreRelease
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build --if-present
      - run: npx release-it --ci --preRelease=${{github.ref_name}} --dry-run
